### ISSUE TITLE
Furnace Upgrade multiple smelting

### ISSUE THREAD

**Issue by Aroma1997** [Aroma1997/BetterChests#4]
Furnace Upgrade smelts Iron Ore into Iron into Refined Iron.
Need way to make it only smelt once.

**Comment by MattsMc** [comment]
Subject Line (for proofing, doesn't show in actual email)
<https://www.digitalocean.com>                         == Deploy a Server
For Free! ==

  Your friend Matthew Smeets has been using DigitalOcean – a cloud
hosting service designed just for developers – and thought you might want
to give it a shot. You can deploy a server in 55 seconds from our control
panel or use our simple API. 

 Because you’ve been invited by a friend, we’d like to give you a $10
credit to try it out. Just use this link to create an account and you’ll
be credited automatically.

 Redeem Your Credit
<https://cloud.digitalocean.com/accept?code=99b0ded4138d53&amp;utm_campaign=Referral_Invite&amp;utm_medium=Referral_Program&amp;utm_source=Mandrill>

  Happy Coding,
 DigitalOcean 

            © DigitalOcean
 Unsubscribe <{% unsubscribe_url %}> <http://do.co/email_twitter>
<http://do.co/email_gplus> <http://do.co/email_facebook>
